**Import atussum_2014.dat by using the file-import-Text Data(delimited), and use personal path to file
import delimited "atussum_2014.dat"

** Lable the varibles
label variable tucaseid   "ATUS Case ID (14-digit identifier)"
label variable gtmetsta   "Metropolitan status (2000 definitions)"
label variable peeduca    "Edited: what is the highest level of school you have completed or the highest degree you have received?"
label variable pehspnon   "Edited: are you Spanish, Hispanic, or Latino?"
label variable ptdtrace   "Race (topcoded)"
label variable teage      "Edited: age"
label variable tehruslt   "Edited: total hours usually worked per week (sum of TEHRUSL1 and TEHRUSL2)"
label variable telfs      "Edited: labor force status"
label variable temjot     "Edited: in the last seven days did you have more than one job?"
label variable teschenr   "Edited: are you enrolled in high school, college, or university?"
label variable teschlvl   "Edited: would that be high school, college, or university?"
label variable tesex      "Edited: sex"
label variable tespempnot "Edited: employment status of spouse or unmarried partner"
label variable trchildnum "Number of household children < 18"
label variable trdpftpt   "Full time or part time employment status of respondent"
label variable trernwa    "Weekly earnings (2 implied decimals)"
label variable trspftpt   "Full time or part time employment status of spouse or unmarried partner"
label variable trsppres   "Presence of the respondent's spouse or unmarried partner in the household"
label variable tryhhchild "Age of youngest household child < 18"
label variable tufinlwgt  "ATUS final weight"
label variable tudiaryday "Day of the week of diary day (day of the week about which the respondent was interviewed)"
label variable trholiday  "Flag to indicate if diary day was a holiday"
label variable trtec      "Total time spent providing eldercare (in minutes)"
label variable trthh      "Total time spent during diary day providing secondary childcare for household children < 13 (in minutes)"

label variable t010101 "Sleeping"
label variable t010102 "Sleeplessness"
label variable t010201 "Washing, dressing and grooming oneself"
label variable t010299 "Grooming, n.e.c.*"
label variable t010301 "Health-related self care"
label variable t010399 "Self care, n.e.c.*"
label variable t010401 "Personal/Private activities"
label variable t010501 "Personal emergencies"
label variable t019999 "Personal care, n.e.c.*"
label variable t020101 "Interior cleaning"
label variable t020102 "Laundry"
label variable t020103 "Sewing, repairing, and maintaining textiles"
label variable t020104 "Storing interior hh items, inc. food"
label variable t020199 "Housework, n.e.c.*"
label variable t020201 "Food and drink preparation"
label variable t020202 "Food presentation"
label variable t020203 "Kitchen and food clean-up"
label variable t020301 "Interior arrangement, decoration, and repairs"
label variable t020302 "Building and repairing furniture"
label variable t020303 "Heating and cooling"
label variable t020399 "Interior maintenance, repair, and decoration, n.e.c.*"
label variable t020401 "Exterior cleaning"
label variable t020402 "Exterior repair, improvements, and decoration"
label variable t020499 "Exterior maintenance, repair and decoration, n.e.c.*"
label variable t020501 "Lawn, garden, and houseplant care"
label variable t020502 "Ponds, pools, and hot tubs"
label variable t020599 "Lawn and garden, n.e.c.*"
label variable t020601 "Care for animals and pets (not veterinary care)"
label variable t020602 "Walking / exercising / playing with animals"
label variable t020699 "Pet and animal care, n.e.c.*"
label variable t020701 "Vehicle repair and maintenance (by self)"
label variable t020799 "Vehicles, n.e.c.*"
label variable t020801 "Appliance, tool, and toy set-up, repair, and maintenance (by self)"
label variable t020901 "Financial management"
label variable t020902 "Household and personal organization and planning"
label variable t020903 "HH and personal mail and messages (except e-mail)"
label variable t020904 "HH and personal e-mail and messages"
label variable t020905 "Home security"
label variable t020999 "Household management, n.e.c.*"
label variable t029999 "Household activities, n.e.c.*"
label variable t030101 "Physical care for hh children"
label variable t030102 "Reading to/with hh children"
label variable t030103 "Playing with hh children, not sports"
label variable t030104 "Arts and crafts with hh children"
label variable t030105 "Playing sports with hh children"
label variable t030106 "Talking with/listening to hh children"
label variable t030108 "Organization and planning for hh children"
label variable t030109 "Looking after hh children (as a primary activity)"
label variable t030110 "Attending hh children's events"
label variable t030111 "Waiting for/with hh children"
label variable t030112 "Picking up/dropping off hh children"
label variable t030199 "Caring for and helping hh children, n.e.c.*"
label variable t030201 "Homework (hh children)"
label variable t030202 "Meetings and school conferences (hh children)"
label variable t030203 "Home schooling of hh children"
label variable t030299 "Activities related to hh child's education, n.e.c.*"
label variable t030301 "Providing medical care to hh children"
label variable t030302 "Obtaining medical care for hh children"
label variable t030303 "Waiting associated with hh children's health"
label variable t030399 "Activities related to hh child's health, n.e.c.*"
label variable t030401 "Physical care for hh adults"
label variable t030402 "Looking after hh adult (as a primary activity)"
label variable t030403 "Providing medical care to hh adult"
label variable t030404 "Obtaining medical and care services for hh adult"
label variable t030405 "Waiting associated with caring for household adults"
label variable t030499 "Caring for household adults, n.e.c.*"
label variable t030501 "Helping hh adults"
label variable t030502 "Organization and planning for hh adults"
label variable t030503 "Picking up/dropping off hh adult"
label variable t030504 "Waiting associated with helping hh adults"
label variable t030599 "Helping household adults, n.e.c.*"
label variable t039999 "Caring for and helping hh members, n.e.c.*"
label variable t040101 "Physical care for nonhh children"
label variable t040102 "Reading to/with nonhh children"
label variable t040103 "Playing with nonhh children, not sports"
label variable t040104 "Arts and crafts with nonhh children"
label variable t040105 "Playing sports with nonhh children"
label variable t040106 "Talking with/listening to nonhh children"
label variable t040108 "Organization and planning for nonhh children"
label variable t040109 "Looking after nonhh children (as primary activity)"
label variable t040110 "Attending nonhh children's events"
label variable t040111 "Waiting for/with nonhh children"
label variable t040112 "Dropping off/picking up nonhh children"
label variable t040199 "Caring for and helping nonhh children, n.e.c.*"
label variable t040201 "Homework (nonhh children)"
label variable t040203 "Home schooling of nonhh children"
label variable t040301 "Providing medical care to nonhh children"
label variable t040302 "Obtaining medical care for nonhh children"
label variable t040303 "Waiting associated with nonhh children's health"
label variable t040401 "Physical care for nonhh adults"
label variable t040402 "Looking after nonhh adult (as a primary activity)"
label variable t040403 "Providing medical care to nonhh adult"
label variable t040404 "Obtaining medical and care services for nonhh adult"
label variable t040405 "Waiting associated with caring for nonhh adults"
label variable t040501 "Housework, cooking, and shopping assistance for nonhh adults"
label variable t040502 "House and lawn maintenance and repair assistance for nonhh adults"
label variable t040503 "Animal and pet care assistance for nonhh adults"
label variable t040504 "Vehicle and appliance maintenance/repair assistance for nonhh adults"
label variable t040505 "Financial management assistance for nonhh adults"
label variable t040506 "Household management and paperwork assistance for nonhh adults"
label variable t040507 "Picking up/dropping off nonhh adult"
label variable t040508 "Waiting associated with helping nonhh adults"
label variable t040599 "Helping nonhh adults, n.e.c.*"
label variable t049999 "Caring for and helping nonhh members, n.e.c.*"
label variable t050101 "Work, main job"
label variable t050102 "Work, other job(s)"
label variable t050103 "Security procedures related to work"
label variable t050104 "Waiting associated with working"
label variable t050199 "Working, n.e.c.*"
label variable t050201 "Socializing, relaxing, and leisure as part of job"
label variable t050202 "Eating and drinking as part of job"
label variable t050203 "Sports and exercise as part of job"
label variable t050205 "Waiting associated with work-related activities"
label variable t050301 "Income-generating hobbies, crafts, and food"
label variable t050302 "Income-generating performances"
label variable t050303 "Income-generating services"
label variable t050304 "Income-generating rental property activities"
label variable t050305 "Waiting associated with other income-generating activities"
label variable t050399 "Other income-generating activities, n.e.c.*"
label variable t050401 "Job search activities"
label variable t050403 "Job interviewing"
label variable t050404 "Waiting associated with job search or interview"
label variable t050499 "Job search and Interviewing, n.e.c.*"
label variable t059999 "Work and work-related activities, n.e.c.*"
label variable t060101 "Taking class for degree, certification, or licensure"
label variable t060102 "Taking class for personal interest"
label variable t060103 "Waiting associated with taking classes"
label variable t060199 "Taking class, n.e.c.*"
label variable t060201 "Extracurricular club activities"
label variable t060202 "Extracurricular music and performance activities"
label variable t060301 "Research/homework for class for degree, certification, or licensure"
label variable t060302 "Research/homework for class for pers. interest"
label variable t060303 "Waiting associated with research/homework"
label variable t060399 "Research/homework n.e.c.*"
label variable t060401 "Administrative activities: class for degree, certification, or licensure"
label variable t060403 "Waiting associated w/admin. activities (education)"
label variable t060499 "Administrative for education, n.e.c.*"
label variable t069999 "Education, n.e.c.*"

** Save to own computer to prepare for mergeing the ATUS datasets 
save "AtusSUM_2014_.dta"