** This .do is made for Stata version 18.0
**Fill in any file path with your own personal one from the downloaded data on github 

*ATUS DATA START 

** Import atuscps_2014.dat by using the file-import-Text Data(delimited)
import delimited "atuscps_2014.dat"

** This lables all the varibles from the data set
label variable gepseucl "Scrambled pseudo primary sampling unit (PSU) cluster"
label variable gepseust "Scrambled pseudo primary sampling unit (PSU) collapsed stratum"
label variable gereg "Region"
label variable gediv "Division"
label variable gestfips "Federal Processing Information Standards (FIPS) state code"
label variable gtmetsta "Metropolitan status (2000 definitions)"
label variable hefaminc "Edited: Family Income"
label variable hehousut "Edited: type of housing unit"
label variable hephoneo "Edited: is a telephone interview acceptable?"
label variable hetelavl "Edited: is there a telephone elsewhere on which people in this household can be contacted?"
label variable hetelhhd "Edited: is there a telephone in this house/apartment?"
label variable hetenure "Edited: are your living quarters owned, rented for cash, or occupied without payment of cash rent?"
label variable hrhhid "Household ID (15-digit identifier)"
label variable hrhhid2 "Household ID part 2 (5-digit identifier)"
label variable hrhtype "Household type"
label variable hrintsta "Interview status"
label variable hrlonglk "Longitudinal link indicator"
label variable hrmis "Month in sample"
label variable hrmonth "Month of interview"
label variable hrnumhou "Total number of persons in the household (household members)"
label variable hryear4 "Year of interview"
label variable hubus "Does anyone in this household have a business or a farm?"
label variable hubusl1 "PULINENO of farm or business owner (first owner)"
label variable hubusl2 "PULINENO of farm or business owner (second owner)"
label variable hubusl3 "PULINENO of farm or business owner (third owner)"
label variable hubusl4 "PULINENO of farm or business owner (fourth owner)"
label variable hufinal "Final outcome code"
label variable huinttyp "Type of interview"
label variable huprscnt "Number of actual and attempted personal contacts"
label variable hurespli "PULINENO of the current respondent"
label variable hutypb "Type B non-interview categories"
label variable hutypc "Type C non-interview categories"
label variable hutypea "Type A non-interview categories"
label variable hxfaminc "HEFAMINC: allocation flag"
label variable hxhousut "HEHOUSUT: allocation flag"
label variable hxphoneo "HEPHONEO: allocation flag"
label variable hxtelavl "HETELAVL: allocation flag"
label variable hxtelhhd "HETELHHD: allocation flag"
label variable hxtenure "HETENURE: allocation flag"
label variable occurnum "Unique person identifier"
label variable peabspdo "Edited: are you being paid by your employer for any of the time off last week?"
label variable peabsrsn "Edited: what was the main reason you were absent from work last week?"
label variable peafever "Edited: did you ever serve on active duty in the U.S. Armed Forces?"
label variable peafnow "Edited: are you now in the Armed Forces?"
label variable peafwhn1 "Edited: when did you serve in the Armed Forces? (first period)"
label variable peafwhn2 "Edited: when did you serve in the Armed Forces? (second period)"
label variable peafwhn3 "Edited: when did you serve in the Armed Forces? (third period)"
label variable peafwhn4 "Edited: when did you serve in the Armed Forces? (fourth period)"
label variable pecohab "Edited: PULINENO of cohabiting partner"
label variable pecyc "Edited: how many years of college credit have you completed?"
label variable pedadtyp "Edited: Is household child a biological, step or adopted child?"
label variable pedipged "Edited: how did you get your high school diploma?"
label variable pedisdrs "Edited: Does this person have difficulty dressing or bathing?"
label variable pedisear "Edited: Is this person deaf or does this person have serious difficulty hearing?"
label variable pediseye "Edited: Is this person blind or does this person have serious difficulty seeing even when wearing glasses?"
label variable pedisout "Edited: Because of a physical, mental, or emotional condition does this person have difficulty doing errands alone such as visiting a doctor's office or shopping?"
label variable pedisphy "Edited: Does this person have serious difficulty walking or climbing stairs?"
label variable pedisrem "Edited: Because of a physical, mental, or emotional condition, does this person have serious difficulty concentrating, remembering, or making decisions?"
label variable pedw4wk "Edited: did you do any of this work during the last 4 weeks?"
label variable pedwavl "Edited: last week, could you have started a job if one had been offered?"
label variable pedwavr "Edited: why could you not have started a job if one had been offered last week?"
label variable pedwlko "Edited: did you look for work any time in the last 12 months?"
label variable pedwlkwk "Edited: and since you left that job or business have you looked for work?"
label variable pedwrsn "Edited: what is the main reason you were not looking for work during the last 4 weeks?"
label variable pedwwk "Edited: did you actually work at a job or business during the last 12 months?"
label variable pedwwnto "Edited: do you currently want a job, either full or part time?"
label variable peeduca "Edited: what is the highest level of school you have completed or the highest degree you have received?"
label variable peern "Edited: total weekly overtime earnings (2 implied decimals)"
label variable peerncov "Edited: on this job, are you covered by a union or employee association contract?"
label variable peernh1o "Edited: excluding overtime pay, tips, and commissions, what is your hourly rate of pay on your main job? (2 implied decimals)"
label variable peernh2 "Edited: excluding overtime pay, tips, and commissions, what is your hourly rate of pay on your main job? (2 implied decimals)"
label variable peernhro "Edited: how many hours do you usually work per week at this rate?"
label variable peernhry "Edited: hourly/non-hourly status"
label variable peernlab "Edited: on this job, are you a member of a labor union or of an employee association similar to a union?"
label variable peernper "Edited: for your main job, what is the easiest way for you to report your total earnings before taxes or other deductions: hourl"
label variable peernrt "Edited: even though you told me it is easier to report your earnings another way, are you paid at an hourly rate on your main jo"
label variable peernuot "Edited: do you usually receive overtime pay, tips, or commissions at your job?"
label variable peernwkp "Edited: how many weeks a year do you get paid?"
label variable pefntvty "Edited: in what country was your father born?"
label variable pegr6cor "Edited: did you complete six or more graduate or professional school courses?"
label variable pegrprof "Edited: since completing your bachelor's degree, have you taken any graduate or professional school courses for credit?"
label variable pehgcomp "Edited: what was the highest grade of regular school you completed before receiving your GED?"
label variable pehract1 "Edited: last week, how many hours did you actually work at your main job?"
label variable pehract2 "Edited: last week, how many hours did you actually work at your other job(s)?"
label variable pehractt "Edited: total hours actually worked last week (sum of PEHRACT1 and PEHRACT2)"
label variable pehravl "Edited: last week, could you have worked full time if the hours had been available?"
label variable pehrftpt "Edited: do you usually work more than 35 hours per week at your job(s)/family business?"
label variable pehrrsn1 "Edited: what is your main reason for working part time?"
label variable pehrrsn2 "Edited: what is the main reason you do not want to work full time?"
label variable pehrrsn3 "Edited: what is the main reason you worked less than 35 hours last week?"
label variable pehrusl1 "Edited: how many hours per week do you usually work at your main job?"
label variable pehrusl2 "Edited: how many hours per week do you usually work at your other job(s)?"
label variable pehruslt "Edited: total hours usually worked per week (sum of PEHRUSL1 and PEHRUSL2)"
label variable pehrwant "Edited: do you want to work a full time work week of 35 hours or more per week?"
label variable pehspnon "Edited: are you Spanish, Hispanic, or Latino?"
label variable peio1cow "Edited: individual class of worker (main job)"
label variable peio1icd "Edited: industry code (main job)"
label variable peio1ocd "Edited: occupation code (main job)"
label variable peio2cow "Edited: individual class of worker (second job)"
label variable peio2icd "Edited: industry code (second job)"
label variable peio2ocd "Edited: occupation code (second job)"
label variable pejhrsn "Edited: what is the main reason you left your last job?"
label variable pejhwant "Edited: do you intend to look for work during the next 12 months?"
label variable pejhwko "Edited: have you worked at a job or business at any time in the last 12 months?"
label variable pelayavl "Edited: could you have returned to work during the last seven days if you had been recalled?"
label variable pelaydur "Edited: duration of layoff (number of weeks)"
label variable pelayfto "Edited: is the job from which you are on layoff a full time job of 35 hours or more per week?"
label variable pelaylk "Edited: even though you are to be called back to work, have you been looking for work during the last 4 weeks?"
label variable pelkavl "Edited: could you have started a job in the last seven days if one had been offered?"
label variable pelkdur "Edited: duration of job seeking (number of weeks)"
label variable pelkfto "Edited: are you seeking a full time or part time job?"
label variable pelkll1o "Edited: before you started looking for work, what were you doing: working, going to school, or something else?"
label variable pelkll2o "Edited: did you lose or quit that job, or was it a temporary job that ended?"
label variable pelklwo "Edited: when did you last work?"
label variable pelkm1 "Edited: what are all of the things you have done to find work during the last 4 weeks? (first method)"
label variable pelndad "Edited: PULINENO of father"
label variable pelnmom "Edited: PULINENO of mother"
label variable pemaritl "Edited: are you now married, widowed, divorced, separated, or never married?"
label variable pemjnum "Edited: altogether, how many jobs did you have?"
label variable pemjot "Edited: in the last seven days, did you have more than one job?"
label variable pemlr "Edited: monthly labor force recode"
label variable pemntvty "Edited: in what country was your mother born?"
label variable pemomtyp "Edited: Is household child a biological, step, or adopted child?"
label variable pems123 "Edited: was your master's degree program a one-year, two-year, or three-year program?"
label variable penatvty "Edited: in what country were you born?"
label variable penlfact "Edited: what best describes your situation at this time? For example, are you disabled, ill, in school, taking care of house or"
label variable penlfjh "Edited: when did you last work at a job or business?"
label variable penlfret "Edited: are you retired from a job or business?"
label variable peparent "Edited: PULINENO of parent"
label variable peret1 "Edited: do you currently want a job, either full or part time?"
label variable perrp "Edited: how is this person related to you?"
label variable peschenr "Edited: last week, were you enrolled in a high school, college, or university?"
label variable peschft "Edited: are you enrolled in school as a full-time or part-time student?"
label variable peschlvl "Edited: would that be high school, college, or university?"
label variable pesex "Edited: sex"
label variable pespouse "Edited: PULINENO of spouse"
label variable prabsrea "Reason not at work by pay status"
label variable pragna "Agricultural/non-agricultural industry"
label variable prcitflg "PRCITSHP: allocation flag"
label variable prcitshp "Citizenship status"
label variable prcivlf "Civilian labor force"
label variable prcow1 "Class of worker recode (main job)"
label variable prcow2 "Class of worker recode (second job)"
label variable prcowpg "Class of worker - private or government"
label variable prdisc "Discouraged worker recode"
label variable prdisflg "Does this person have any of these disability conditions?"
label variable prdtcow1 "Detailed class of worker recode (main job)"
label variable prdtcow2 "Detailed class of worker recode (second job)"
label variable prdthsp "Detailed Hispanic origin group"
label variable prdtind1 "Detailed industry recode (main job)"
label variable prdtind2 "Detailed industry recode (second job)"
label variable prdtocc1 "Detailed occupation recode (main job)"
label variable prdtocc2 "Detailed occupation recode (second job)"
label variable premp "Employed persons recode"
label variable premphrs "Reason not at work or hours at work"
label variable prempnot "Employed, unemployed, or not in the labor force"
label variable prerelg "Earnings edit eligibility flag"
label variable prernhly "Hourly earnings at main job (2 implied decimals)"
label variable prernwa "Weekly earnings at main job (2 implied decimals)"
label variable prexplf "Experienced labor force employment"
label variable prfamnum "Family number recode"
label variable prfamrel "Family relationship code"
label variable prfamtyp "Family type recode"
label variable prftlf "Full time labor force"
label variable prhernal "PRERNHLY: allocation flag"
label variable prhrusl "Usual hours worked weekly"
label variable primind1 "Intermediate industry recode (main job)"
label variable primind2 "Intermediate industry recode (second job)"
label variable prinuyer "Immigrant's year of entry into the U.S."
label variable prioelg "Industry and occupation edit eligibility flag"
label variable prjobsea "Job search recode"
label variable prmarsta "Marital status based on Armed Forces participation"
label variable prmjind1 "Major industry recode (main job)"
label variable prmjind2 "Major industry recode (second job)"
label variable prmjocc1 "Major occupation recode (main job)"
label variable prmjocc2 "Major occupation recode (second job)"
label variable prmjocgr "Major occupation categories (main job)"
label variable prnagpws "Non-agricultural private wage and salary workers recode"
label variable prnagws "Non-agricultural wage and salary workers recode"
label variable prnlfsch "Not in labor force activity - in school or not in school"
label variable prnmchld "Number of own children < 18 years of age"
label variable prpertyp "Type of person recode"
label variable prpthrs "At work 1-34 hours by hours at work"
label variable prptrea "Detailed reason for part time work"
label variable prsjmj "Single/multiple jobholder"
label variable prtage "Age"
label variable prtfage "Topcode for age (PRTAGE)"
label variable prunedur "Duration of unemployment (number of weeks)"
label variable pruntype "Reason for unemployment"
label variable prwernal "PRERNWA: allocation flag"
label variable prwksch "Labor force by time worked or lost"
label variable prwkstat "Full time or part time work status"
label variable prwntjob "Not in labor force recode - want a job or other not in labor force"
label variable ptdtrace "Race (topcoded)"
label variable pthr "Hourly pay topcode flag"
label variable ptot "Weekly overtime amount topcode flag"
label variable ptwk "Weekly earnings topcode flag"
label variable puabsot "In the last seven days, did you have a job either full or part time?"
label variable pubus1 "Last week, did you do any unpaid work in the family business or farm?"
label variable pubus2ot "Do you receive any payments or profits from the business?"
label variable pubusck1 "Business check item 1: filter for questions on unpaid work"
label variable pubusck2 "Business check item 2: skips owners of family business who did not work last week"
label variable pubusck3 "Business check item 3: filter for disabled"
label variable pubusck4 "Business check item 4: filter for retired"
label variable puchinhh "Change in household composition"
label variable pudis "Last time we spoke to someone in this household, you were reported to have a disability. Does your disability continue to preven"
label variable pudis1 "Does your disability prevent you from accepting any kind of work during the next six months?"
label variable pudis2 "Do you have a disability that prevents you from accepting any kind of work during the next six months?"
label variable pudwck1 "Discouraged worker check item 1: filter for discouraged worker"
label variable pudwck2 "Discouraged worker check item 2: filter for disabled"
label variable pudwck3 "Discouraged worker check item 3: filter for retired"
label variable pudwck4 "Discouraged worker check item 4: filter for passive job seekers"
label variable pudwck5 "Discouraged worker check item 5: filter for passive job seekers"
label variable puern2 "Weekly overtime earnings (2 implied decimals)"
label variable puernh1c "What is your hourly rate of pay on this job, excluding overtime pay, tips, or commissions? (2 implied decimals)"
label variable puhrck1 "Hours respondent check item 1: labor force - remove groups from actual hours series"
label variable puhrck12 "Hours respondent check item 12: filter for < 15 hours to go to looking series"
label variable puhrck2 "Hours respondent check item 2: labor force - skips persons responding yes to PUHRFTPT out of PT series"
label variable puhrck3 "Hours respondent check item 3: labor force - filter for persons going through industry and occupation series"
label variable puhrck4 "Hours respondent check item 4: labor force - skips persons"
label variable puhrck5 "Hours respondent check item 5: labor force - filter for multiple jobholders for second job hours"
label variable puhrck6 "Hours respondent check item 6: labor force - filter for actual job hours, jobs 1 and 2"
label variable puhrck7 "Hours respondent check item 7: labor force - filter for hours worked paths"
label variable puhroff1 "Last week, did you lose or take off any hours from your job for any reason such as illness, slack work, vacation, or holiday?"
label variable puhroff2 "How many hours did you take off?"
label variable puhrot1 "Last week, did you work any overtime or extra hours? (main job)"
label variable puhrot2 "How many additional hours did you work?"
label variable puio1mfg "Is this business or organization mainly manufacturing, retail trade, wholesale trade, or something else? (main job)"
label variable puio2mfg "Is this business or organization mainly manufacturing, retail trade, wholesale trade, or something else? (second job)"
label variable puiock1 "Industry and occupation check item 1: filter for dependent industry and occupation"
label variable puiock2 "Industry and occupation check item 2: filter for previous month's industry and occupation cases"
label variable puiock3 "Industry and occupation check item 3: filter for previous month's unknown occupation"
label variable puiodp1 "Last month you were reported to work for (employer's name). Do you still work for (employer's name)?"
label variable puiodp2 "Have the usual activities and duties of your job changed since last month?"
label variable puiodp3 "Last time you were reported as (occupation) and your usual duties were (activities). Is this an accurate description of your cur"
label variable pujhck1 "Job history check item 1: filter for outgoing rotations"
label variable pujhck2 "Job history check item 2: filter for persons going through industry and occupation series"
label variable pujhck3 "Job history check item 3: filter for unemployed job history"
label variable pujhck4 "Job history check item 4: filter for dependent not in the labor force"
label variable pujhck5 "Job history check item 5: filter/carryover for dependent not in the labor force"
label variable pujhdp1o "Did you do any of this work in the last 4 weeks?"
label variable pulay "During the last seven days, were you on layoff from a job?"
label variable pulay6m "Have you been given any indication that you will be recalled to work within the next 6 months?"
label variable pulayavr "Why could you not have started a job in the last week?"
label variable pulayck1 "Layoff check item 1: filter for previous month layoff status"
label variable pulayck2 "Layoff check item 2: filter for dependent layoff"
label variable pulayck3 "Layoff check item 3: dependent industry and occupation filter/carryover"
label variable pulaydt "Has your employer given you a date to return to work? (to layoff job)"
label variable pulineno "Person line number"
label variable pulk "Have you been doing anything to find work during the last 4 weeks?"
label variable pulkavr "Why could you not have started a job last week?"
label variable pulkdk1 "You said you have been trying to find work. How did you go about looking? (first method)"
label variable pulkdk2 "PULKDK1 text: (second method)"
label variable pulkdk3 "PULKDK1 text: (third method)"
label variable pulkdk4 "PULKDK1 text: (fourth method)"
label variable pulkdk5 "PULKDK1 text: (fifth method)"
label variable pulkdk6 "PULKDK1 text: (sixth method)"
label variable pulkm2 "What are all of the things you have been doing to find work during the last 4 weeks? (second method)"
label variable pulkm3 "PULKM2 text: (third method)"
label variable pulkm4 "PULKM2 text: (fourth method)"
label variable pulkm5 "PULKM2 text: (fifth method)"
label variable pulkm6 "PULKM2 text: (sixth method)"
label variable pulkps1 "Can you tell me more about what you did to search for work? (first method)"
label variable pulkps2 "PULKPS1 text: (second method)"
label variable pulkps3 "PULKPS1 text: (third method)"
label variable pulkps4 "PULKPS1 text: (fourth method)"
label variable pulkps5 "PULKPS1 text: (fifth method)"
label variable pulkps6 "PULKPS1 text: (sixth method)"
label variable punlfck1 "Not in labor force check item 1: age filter for retirement question"
label variable punlfck2 "Not in labor force check item 2: outgoing rotation filter"
label variable puretot "Last month you were reported to be retired. Are you still retired?"
label variable puslfprx "Labor force information collected by self or proxy response"
label variable puwk "Last week, did you do any work for either pay or profit?"
label variable pxabspdo "PEABSPDO: allocation flag"
label variable pxabsrsn "PEABSRSN: allocation flag"
label variable pxafever "PEAFEVER: allocation flag"
label variable pxafnow "PEAFNOW: allocation flag"
label variable pxafwhn1 "PEAFWHN1: allocation flag"
label variable pxage "PRTAGE: allocation flag"
label variable pxcohab "PECOHAB: allocation flag"
label variable pxcyc "PECYC: allocation flag"
label variable pxdadtyp "PEDADTYP: allocation flag"
label variable pxdipged "PEDIPGED: allocation flag"
label variable pxdisdrs "PEDISDRS: allocation flag"
label variable pxdisear "PEDISEAR: allocation flag"
label variable pxdiseye "PEDISEYE: allocation flag"
label variable pxdisout "PEDISOUT: allocation flag"
label variable pxdisphy "PEDISPHY: allocation flag"
label variable pxdisrem "PEDISREM: allocation flag"
label variable pxdw4wk "PEDW4WK: allocation flag"
label variable pxdwavl "PEDWAVL: allocation flag"
label variable pxdwavr "PEDWAVR: allocation flag"
label variable pxdwlko "PEDWLKO: allocation flag"
label variable pxdwlkwk "PEDWLKWK: allocation flag"
label variable pxdwrsn "PEDWRSN: allocation flag"
label variable pxdwwk "PEDWWK: allocation flag"
label variable pxdwwnto "PEDWWNTO: allocation flag"
label variable pxeduca "PEEDUCA: allocation flag"
label variable pxern "PEERN: allocation flag"
label variable pxerncov "PEERNCOV: allocation flag"
label variable pxernh1o "PEERNH1O: allocation flag"
label variable pxernh2 "PEERNH2: allocation flag"
label variable pxernhro "PEERNHRO: allocation flag"
label variable pxernhry "PEERNHRY: allocation flag"
label variable pxernlab "PEERNLAB: allocation flag"
label variable pxernper "PEERNPER: allocation flag"
label variable pxernrt "PEERNRT: allocation flag"
label variable pxernuot "PEERNUOT: allocation flag"
label variable pxernwkp "PEERNWKP: allocation flag"
label variable pxfntvty "PEFNTVTY: allocation flag"
label variable pxgr6cor "PEGR6COR: allocation flag"
label variable pxgrprof "PEGRPROF: allocation flag"
label variable pxhgcomp "PEHGCOMP: allocation flag"
label variable pxhract1 "PEHRACT1: allocation flag"
label variable pxhract2 "PEHRACT2: allocation flag"
label variable pxhractt "PEHRACTT: allocation flag"
label variable pxhravl "PEHRAVL: allocation flag"
label variable pxhrftpt "PEHRFTPT: allocation flag"
label variable pxhrrsn1 "PEHRRSN1: allocation flag"
label variable pxhrrsn2 "PEHRRSN2: allocation flag"
label variable pxhrrsn3 "PEHRRSN3: allocation flag"
label variable pxhrusl1 "PEHRUSL1: allocation flag"
label variable pxhrusl2 "PEHRUSL2: allocation flag"
label variable pxhruslt "PEHRUSLT: allocation flag"
label variable pxhrwant "PEHRWANT: allocation flag"
label variable pxhspnon "PEHSPNON: allocation flag"
label variable pxinusyr "PRINUYER: allocation flag"
label variable pxio1cow "PEIO1COW: allocation flag"
label variable pxio1icd "PEIO1ICD: allocation flag"
label variable pxio1ocd "PEIO1OCD: allocation flag"
label variable pxio2cow "PEIO2COW: allocation flag"
label variable pxio2icd "PEIO2ICD: allocation flag"
label variable pxio2ocd "PEIO2OCD: allocation flag"
label variable pxjhrsn "PEJHRSN: allocation flag"
label variable pxjhwant "PEJHWANT: allocation flag"
label variable pxjhwko "PEJHWKO: allocation flag"
label variable pxlayavl "PELAYAVL: allocation flag"
label variable pxlaydur "PELAYDUR: allocation flag"
label variable pxlayfto "PELAYFTO: allocation flag"
label variable pxlaylk "PELAYLK: allocation flag"
label variable pxlkavl "PELKAVL: allocation flag"
label variable pxlkdur "PELKDUR: allocation flag"
label variable pxlkfto "PELKFTO: allocation flag"
label variable pxlkll1o "PELKLL1O: allocation flag"
label variable pxlkll2o "PELKLL2O: allocation flag"
label variable pxlklwo "PELKLWO: allocation flag"
label variable pxlkm1 "PELKM1: allocation flag"
label variable pxlndad "PELNDAD: allocation flag"
label variable pxlnmom "PELNMOM: allocation flag"
label variable pxmaritl "PEMARITL: allocation flag"
label variable pxmjnum "PEMJNUM: allocation flag"
label variable pxmjot "PEMJOT: allocation flag"
label variable pxmlr "PEMLR: allocation flag"
label variable pxmntvty "PEMNTVTY: allocation flag"
label variable pxmomtyp "PEMOMTYP: allocation flag"
label variable pxms123 "PEMS123: allocation flag"
label variable pxnatvty "PENATVTY: allocation flag"
label variable pxnlfact "PENLFACT: allocation flag"
label variable pxnlfjh "PENLFJH: allocation flag"
label variable pxnlfret "PENLFRET: allocation flag"
label variable pxparent "PEPARENT: allocation flag"
label variable pxrace1 "PTDTRACE: allocation flag"
label variable pxret1 "PERET1: allocation flag"
label variable pxrrp "PERRP: allocation flag"
label variable pxschenr "PESCHENR: allocation flag"
label variable pxschft "PESCHFT: allocation flag"
label variable pxschlvl "PESCHLVL: allocation flag"
label variable pxsex "PESEX: allocation flag"
label variable pxspouse "PESPOUSE: allocation flag"
label variable qstnum "Unique household identifier"
label variable tratusr "ATUS respondent"
label variable tucaseid "ATUS Case ID (14-digit identifier)"
label variable tulineno "ATUS person line number"
label variable prdasian "Detailed Asian race recode"
label variable pepdemp1 "Does this person usually have any paid employees?"
label variable ptnmemp1 "Excluding all owners, how many paid employees does this person usually have?"
label variable pepdemp2 "Does this person usually have any paid employees?"
label variable ptnmemp2 "Excluding all owners, how many paid employees does this person usually have?"
label variable pxpdemp1 "PEPDEMP1: allocation flag"
label variable pxnmemp1 "PTNMEMP1: allocation flag"
label variable pxpdemp2 "PEPDEMP2: allocation flag"
label variable pxnmemp2 "PTNMEMP2: allocation flag"

** Save to own computer to prepare for mergeing the 2 ATUS datasets 

save "AtusCPS_2014_.dta"

